### ISSUE TITLE
Adjust threshold for equilibrium

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#137]
Related to #130 

The equilibrium statements seem to occur about ~0.1* early. There is a threshold to define equilibrium, which can be tuned. Self-assigning to investigate and make a recommendation.

**Comment by jbphet** [comment]
I have adjusted the default values to the ones that @arouinfar recommended above.  I'm reluctant to remove the query parameters at this time, since it's possible that more refinement might be necessary before the sim is published, so I have left them in place and marked them with `TODO`s, and will pull them into the code when we are closer to publication.  Deferring for now.

**Comment by jbphet** [comment]
These constants have been pulled into the main code, closing.
