### ISSUE TITLE
Add propagation effect to waves

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#15]
To make the propagation feel less like an animation and somewhat more random, we'd like to add another propagation effect to the waves demo.

A few seconds after a wave has fully propagated across the screen, we'd like to turn it off. The wave's tail would then be seen approaching the its end point. Here's are some rough sketches of what I think it'd look like for a single wave. Time is progressing to the right in these images.
![image](https://user-images.githubusercontent.com/8419308/80656658-ef8fb700-8a3e-11ea-81e2-8730aad53b3e.png)
![image](https://user-images.githubusercontent.com/8419308/80656958-a0965180-8a3f-11ea-8711-2c0b7c5ac581.png)

A few seconds after turning off a wave (but while it's still progressing off-screen) we'd like to turn on a new wave to take its place.  The new wave would be close to, but not in the exact same position, as the wave that was turned off.  The set of possible wave positions could be something like this:

![image](https://user-images.githubusercontent.com/8419308/80657265-60839e80-8a40-11ea-8956-57f84499b4a6.png)

For simplicity, I think we'd only want one set of waves leaving/entering the screen at a given time.

During brainstorming meeting, we decided that @samreid would continue to work on the prototype on his own, since we're still fairly far out from starting development. We would like to review this iteration in the 5/12 brainstorming meeting, so marking as high priority.

@samreid please let me know if you have any questions, or if you would like to have another zoom chat.

**Comment by samreid** [comment]
Notes from today's meeting with @kathy-phet and @arouinfar 

Make it so that when the yellow tail comes onscreen, that triggers the creation of the next yellow (about an inch away).  Same for reds.
> Detect when the tail emits the surface, then start a new red wave.  When you have 2 waves overlapping it is too confusing

make the left red wave move to the left, so they spread out from the center, to reduce the overlap

Change the reflected red wave on the left to go directly down (0 degress to normal)

Red wave transmitted angle should be the same as red wave incident angle
-should look same (continued wave) but a change in intensity

SR: Should I match those phases for tomorrow's meeting?
KP: Not necessary for discussion, but try to get propagation working for the reds.

KP: Wire up "pause" for each wave type.  Get rid of "beam" and "hidden"

AR: Can everything be in steady state, except for a few gaps?
KP: Gaps could happen anywhere, but they are less frequent.
KP: Only one red and one yellow should be able to show a transient at one time.  

KP: Add a checkbox that says "show gaps" that lets you toggle between steady state and showing gaps.

- [x] Move the members of the yellow pair closer to each other

- [x] keep the zigzag

**Comment by samreid** [comment]
From slack:

@samreid said:
I’m at a good point on Greenhouse, and thought it might be helpful if you want to take another quick look before tomorrow’s design meeting.

@arouinfar said:
Master is looking nice! I don’t think the Show Gaps checkbox does anything, though. (edited) 

@samreid replied:
Right, that is my last checkbox.  I should have that working momentarily.  Is everething else good enough for tomorrow?

@arouinfar replied
I think so, but it might be nice for @kathy-phet to take a look too.

@samreid 
The most efficient way I could get “Show Gaps” checkbox to work requires resetting the model.  It’s committed if you want to test it out.  I’ll presume everything is set for Tuesday unless I hear otherwise.  I also want to let you know what this implementation models the lengths of the waves and I set them up so the gaps are staggered.

**Comment by samreid** [comment]
At today's design meeting, we agreed the prototype is sufficiently advanced for the design of the sim, and no further work was requested.  Closing.
