### ISSUE TITLE
Updates to Explore Mode RadioButtonGroup responsive descriptions

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#150]
For #130 

Currently, when switching between the Explore Mode radio buttons, this is read out:
Now {{value}} levels of greenhouse gases.

This is problematic when switching to the time period mode, so we would like to instead state that the concentration is simply higher or lower:
Now {{higher/lower}} levels of greenhouse gases.

When switching back to the slider mode, the response will state the current value, as it currently does, e.g. “Now moderate levels of greenhouse gases.” (No changes necessary in this direction.)

**Comment by jbphet** [comment]
Questions about this:
- When saying higher/lower, is that with respect to the previous setting in the manual mode?
- What should we do in the case where the manual mode is the same or very close to the value in the time-period mode?  Should there be a range in which the word "similar" is used instead of higher and lower?
- Should we consider using the recently added "historical" terminology instead of the comparative wording?  For example, saying "Now historically low levels of greenhouse gases".

**Comment by arouinfar** [comment]
Unassigning myself since we discussed this over zoom. Let me know if more questions pop up.

**Comment by jbphet** [comment]
This is implemented on master.  @arouinfar - please take it for a test drive and close if it looks good.

**Comment by arouinfar** [comment]
Thanks @jbphet! I spent awhile trying to trigger the "unchanged" statement, but realized the `concentrationProperty` likely shifted to address the equilibrium temperature in #121 and there is no longer a correspondence between the dates and the values accessible to the slider. Anyway, the behavior in master looks good and behaves as expected (given updated concentrations), so closing.
