### ISSUE TITLE
Reconsider "blinking" IR photon effect on Photon Screen

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/greenhouse-effect#163]
In 5/25/22 GHE meeting, we discussed that the complete disappearing and reappearing effect of the IR photons in the Photon Screen (where you cannot see the absorbing layers) seemed a bit hard to talk around. And the suggestion was to consider just a redirection of the photon, without a disappearance. Or maybe a bit of a fade so you can see something? 

Maybe also do this on the Layers Screen. But it could also be different on the two screens.

**Comment by jbphet** [comment]
During today's design meeting I went ahead and turned off the blinking since it was a simple change.  Seems like an improvement to me (and Mark N said so too), but it probably would be good to have some sort of effect rather than just the change in direction to make it a little more eye-catching.

**Comment by arouinfar** [comment]
@jbphet @kathy-phet I think that removing the blink is a good call, and it's certainly easier to follow on the Photons screen.

> Or maybe a bit of a fade so you can see something?

I like the idea of a fade, maybe we could reduce the opacity for a frame or two before the photon redirects?

I'm having a hard time tracking the photons on the Layer Model screen. Part of it is due to the time delay between the photon's absorption and emission, but the photon also appears to move a bit in the x-direction when emitted. 

Tagging for design meeting to continue the discussion.

**Comment by jbphet** [comment]
I've changed the absorption times and jump distances for the photons to zero, and also made the layers very thin in terms of where they absorb photons.  This gets rid of the blinking effect, and makes it easier to follow the photons, but we want to see if we can come up with something that makes it more apparent that something is happening other than the photons just bouncing around.  We will track this in #167.  Closing this one.
