### ISSUE TITLE
Options Dialog should be removed from PhET menu

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#168]
**Problem description**
For https://github.com/phetsims/qa/issues/811

The options dialog should be removed. 
@arouinfar confirmed on slack that the information currently in the options dialog (sounds and mockup) should not be user facing. 

**Visuals**
<img width="805" alt="Screen Shot 2022-06-13 at 2 54 40 PM" src="https://user-images.githubusercontent.com/87318828/173424994-1364b069-3366-4a97-84e6-aeff940627b2.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.9/phet/greenhouse-effect_all_phet.html?screens=1
Version: 1.1.0-dev.9 2022-06-08 20:37:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Language: en-US
Window: 1371x702
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jbphet** [comment]
Good observation @Nancy-Salpepi.  I don't want to get rid of the dialog altogether, since we may still use it before we're ready to publish the sim, so I put it behind a query parameter.  The query parameter is a flag, and it is called `optionsDialog`.  I also created a new GitHub issue to remind me to remove the dialog prior to full publication, see https://github.com/phetsims/greenhouse-effect/issues/179.

@Nancy-Salpepi - Please test this out on master and verify that the menu option and the dialog are not present when the query parameter isn't used, which is the nominal case.  If it looks good, this can be closed.

**Comment by Nancy-Salpepi** [comment]
Looks good on master. "Options" is no longer an option 🤣 in the PhET menu without the query parameter.

**Comment by jbphet** [comment]
I've decided to reopen this and have it verified on the next dev release.  Seems like the right thing to do.

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.

**Comment by jbphet** [comment]
There is another issue that already exists about removing the sim-specific options UI, see https://github.com/phetsims/greenhouse-effect/issues/179.  I've updated the TODOs in the code to reference that issue instead, since it seems more appropriate.  Closing this one.
