### ISSUE TITLE
Add keyboard help information for interaction with the flux meter

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#180]
Interaction with the flux meter will need some custom explanations in the Keyboard Help dialog.  This should be designed first, then implemented.

Assigning to @arouinfar for the design part.

**Comment by arouinfar** [comment]
The current plan is to implement the probe as an accessible slider. In that case, we may not need specific content for the Energy Flux Meter.

**Comment by arouinfar** [comment]
Tagging for design meeting. The current implementation uses a slider, so I don't think we need specific information in the keyboard help dialog, but let's confirm with the team.

**Comment by jbphet** [comment]
At today's meeting we decided that we would change the heading for the Slider Controls in the keyboard help dialog to say "Slider and Flux Meter" controls.  This pertains to the screens that include a flux meter, which are the Photons and Layer Model screens.

**Comment by jbphet** [comment]
@arouinfar - I just did some investigation into changing the keyboard help dialog section that says "Slider Controls" to "Slider and Flux Meter Controls".  The title string "Slider Controls" comes from a common code component called `SliderControlsKeyboardHelpSection` in scenery-phet, and there does not seem to be an option to change the value in the constructor.  I have two questions about this for you:

1. I'm going to assume that this is not blocking for the upcoming prototype release in #220.  Agreed?
2. Is this something we can simply do without, or should I create a common code issue and have someone make this an option for this dialog section?  There would obviously be some complications to doing this, since providing a separate property to override the default might be confusing to anyone using phet-io to adjust strings.  This isn't a deal breaker, but I thought it should feed into the decision.

**Comment by arouinfar** [comment]
Thanks for investigating @jbphet.

> 1.  I'm going to assume that this is not blocking for the upcoming prototype release in https://github.com/phetsims/greenhouse-effect/issues/220. Agreed?

I completely agree. This is not important for the prototype.

> 2. Is this something we can simply do without, or should I create a common code issue and have someone make this an option for this dialog section? There would obviously be some complications to doing this, since providing a separate property to override the default might be confusing to anyone using phet-io to adjust strings. This isn't a deal breaker, but I thought it should feed into the decision.

It seems like there should be an option in `SliderControlsKeyboardHelpSection` to provide a custom title. I'm surprised this doesn't already exist. There are sims that use slider interactions without having any visual sliders in the sim, such as Gravity Force Lab: Basics. In GFLB, there is a "Move Spheres" section in the keyboard help dialog, but perhaps this is a completely custom section and unrelated to `SliderControlsKeyboardHelpSection`.
<img width="459" alt="image" src="https://user-images.githubusercontent.com/8419308/209020772-dbd99bbe-a559-40ed-b3f8-56c970d1b265.png">

I think the only PhET-iO implication is that the title string would live under `model.strings.simName` instead of `model.strings.sceneryPhet`.  This seems like an acceptable trade-off to me.

@jbphet please open up a general issue.

**Comment by jbphet** [comment]
@arouinfar - You were right, an option to change the section's title does exist, and I just missed it.  I've made the changes, including some additional ones that you and I discussed over Slack.  Please have a look and let me know if we're good to go.

**Comment by arouinfar** [comment]
@jbphet the heading and contents look good, for Photons and Layer Model. However, there isn't a Flux Meter on the Waves screen, so it should just be the default `SliderControlsKeyboardHelpSection`.

**Comment by jbphet** [comment]
> However, there isn't a Flux Meter on the Waves screen, so it should just be the default `SliderControlsKeyboardHelpSection`.

Good point.  I'd missed that, and have corrected it.  The commits above should be cherry-picked to the release branch so that it is fixed in the prototype when deployed.

**Comment by jbphet** [comment]
These changes have been propagated to the 1.1 branch.  This should be verified before publication of the 1.1 prototype.

**Comment by Nancy-Salpepi** [comment]
This is what I see in rc.2:
-On the Photons and Layer Model Screens, the title is "Slider and Flux Meter Controls" (This change happened before rc.1)
-On the Photons and Layer Model Screens, "adjust slider" is just "adjust" (This change happened before rc.1)
-On the Waves Screen, the title has been changed back to the default "Slider Controls"
-On the Waves Screen, it says "adjust slider"
-The button correctly says "Option" when using a mac (yay!) instead of "alt"

I believe this list covers everything discussed in the issue, so closing.
