### ISSUE TITLE
Final temperature read out may be .1 or .2 degrees off

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#184]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/811. Seen with Chrome + Jaws. It can also occur in the a11y view.
When Fahrenheit is enabled, the final "steady temperature" and even the degrees in the scene description, may be different from the temperature displayed in the sim by .1 or .2 degrees. The bellow image does not capture the difference in the description, though that also happens. It only shows the potentially incorrect alert.

**Visuals**
<img width="947" alt="degrees" src="https://user-images.githubusercontent.com/41024075/174388237-8f0b61b2-dc4e-4d88-b269-4e351cac636a.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.9/phet/greenhouse-effect_all_phet.html?screens=1
Version: 1.1.0-dev.9 2022-06-08 20:37:50 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe. 

Looks like the "Surface temperature stable" response is off about ~25% of the time when using Fahrenheit. There is a threshold for defining equilibrium that requires the energy to be within a certain level `atEquilibriumThreshold` for some amount of time `atEquilibriumTime`. These parameters were tuned in #137, but I was focused on C/K at the time. An increase in 1 degree Fahrenheit corresponds to a larger energy increase than an increase in 1 degree C, which is why we see some disagreement between the alert and the true equilibrium temperature. 

@jbphet I experimented with the `atEquilibriumThreshold` and `atEquilibriumTime` query parameters to see if I could improve the experience for Fahrenheit. Let's increase `atEquilibriumTime` to 2 seconds. It seems to eliminate the mismatched alert/temperature, but without having noticeable effects elsewhere in the responsive descriptions.

**Comment by jbphet** [comment]
This change is now implemented on master.  @arouinfar - Please check it and make sure it seems correct, then feel free to close this issue.

**Comment by arouinfar** [comment]
Thanks @jbphet. The mismatch for Fahrenheit still exists, but occurs less frequently and is never off by more than 0.1°.

A side effect of this change is that users are now more likely to encounter two responsive descriptions with the same temperature -- one with the heating/cooling language, and one where it is stable. I think this is an acceptable trade-off, but it also means that I don't think we should lengthen `atEquilibriumTime` any further. 

```
Surface temperature stable at 8.1 degrees Fahrenheit.
Cooling, now 8.1 degrees Fahrenheit.
```

**Comment by arouinfar** [comment]
How often do you see it @KatieWoe? Is it frequent or just once in a while? I'm fine with the latter.

**Comment by KatieWoe** [comment]
I saw it once while testing, but it wasn't a large sample size due to difficulty getting alerts and temp reading in https://github.com/phetsims/greenhouse-effect/issues/195.
