### ISSUE TITLE
Add a query parameter for default temperature units

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#186]
This has been done for other sims (I think SOM is an example), so we should do it in a similar way.

**Comment by jbphet** [comment]
I just looked through the code base, and I'm not finding a precedent for being able to set the units to any of the allowable values.  Instead, in state-of-matter and number-line-integers, I'm seeing a parameter called `defaultCelsius`.  For some history relative to states-of-matter, please see https://github.com/phetsims/states-of-matter/issues/216.

I'm going to start of with a different approach here.  I'll create a query parameter called `defaultTemperatureUnits` and will allow it to take 'F', 'C', or 'K' as values, and go from there.

**Comment by jbphet** [comment]
@arouinfar - This is now implemented as described in the previous comment.  It works for the first two screens, but not for the third one, since temperature units control is not yet implemented for that screen.  Please check it out, and let me know if this seems like it will work.  We can change the query parameter and values if you have thoughts on how to improve it.

**Comment by arouinfar** [comment]
> I'm going to start of with a different approach here. I'll create a query parameter called defaultTemperatureUnits and will allow it to take 'F', 'C', or 'K' as values, and go from there.

This looks great to me @jbphet. I opened up https://github.com/phetsims/states-of-matter/issues/361 to do the same in SOM(B) when it's republished off of master.

I don't think there's anything else we need to do for this issue, since adding a user-facing control to the Options/Preferences dialog is being tracked in https://github.com/phetsims/greenhouse-effect/issues/187.
