### ISSUE TITLE
Incorrect surface temperature response sometimes uttered

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#193]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
safari/chrome

**Problem description**
For https://github.com/phetsims/qa/issues/819 If I change the concentration value just before "warming/cooling" is uttered, the surface temperature statement will be incorrect. For example, if I increased the concentration by one step just before "cooling" is uttered, I will see/hear:
                    
<img width="399" alt="Screen Shot 2022-07-15 at 8 53 22 AM" src="https://user-images.githubusercontent.com/87318828/179226958-5432412f-4eb8-4e2d-81fb-2a46b973deed.png">

Sometimes, no surface temperature statement is uttered.
This is seen with a11y view and with VO. 

**Steps to reproduce**
1. In a11y view, tab to and press the Start Sunlight button
2. Tab to the Concentration Slider 
3. Once "warming" appears in the activity log, decrease the concentration to "None"
4. After the 3 statements appear in the activity log (IR redirecting, surface temp, IR emitting) increase the concentration value by pressing the Up Arrow once. 
5. After the 3 statements, press the Down Arrow once.

It might take a few tries repeating steps 4 and 5 until you see the error. 

**Visuals**

https://user-images.githubusercontent.com/87318828/179225507-b49a1b6a-fa39-4915-aa52-a543611179bf.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.10/phet/greenhouse-effect_en_phet.html?postMessageOnLoad&postMessageOnError&supportsInteractiveDescription=true
Version: 1.1.0-dev.10 2022-07-08 17:41:59 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language: en-US
Window: 2160x1047
Pixel Ratio: 1.3333333730697632/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
This is happening because of the interval at which we announce and save values to alerts. Whenever we create an alert, we save model values and describe what has happened since the last time we made an alert. Whenever we change the concentration we wait 2 seconds for the model to change before making an alert. But we still describe things relative to the previous alert. 

I drew this plot to help me understand - The description at the third red tick after increasing the concentration will be relative to the description at the second red tick. Indeed, temperatures ARE lower between these two points.

![image](https://user-images.githubusercontent.com/6396244/181269298-d97ad3eb-3ba3-4155-8565-84e35fdb3c42.png)

We might improve this behavior by resetting variables when the concentration changes so that descriptions are relative to the model at that event instead of relative to the last time a description was generated. If the model is slow to respond (like in my graph) it wouldn't change the output. But it probably would in many cases.

@arouinfar should we do this? I also wondered if the current behavior is actually correct because we are indicating that the temperatures are changing over time in response to concentration changes.

**Comment by jessegreenberg** [comment]
Thinking about this more, I think this is just the natural behavior of the model and it is describing the plot in https://github.com/phetsims/greenhouse-effect/issues/193#issuecomment-1196824854 correctly. I wouldn't recommend changing how it is described but let me know what you think @arouinfar .

**Comment by jbphet** [comment]
This was discussed in the 7/27/2022 design meeting, and we decided that this problem does not block the planned interviews.  We have some thoughts on how to simplify the alerts and thus partially address this behavior, and some thoughts on what to put in the Teacher Tips doc.  @arouinfar will elaborate.

**Comment by jbphet** [comment]
The design team discussed this in today's meeting, and decided that this is the desired change: Add a delay of a few seconds after a change to the gas concentration that prevents context responses about the surface temperature from being put into the utterance queue for a few seconds.  This will allow the other messages, such as "More infrared radiation being emitted from surface", to have time to be processed, which should hopefully be less confusing.

**Comment by jessegreenberg** [comment]
The delay in temperature alerts was added in the above commit. @arouinfar @Matthew-Moore240 would you mind testing this change out?

**Comment by jessegreenberg** [comment]
Actually, hold on review for a moment, I see overlap with this and what is requested her and https://github.com/phetsims/greenhouse-effect/issues/199.

**Comment by jessegreenberg** [comment]
@arouinfar and I discussed over a zoom call and reviewed the current sim behavior and descriptions. We agreed not to do anything for this issue and accept it as the natural behavior of the model. We tried to increase the delay before describing temperatures and still saw this behavior. It was esecially noticeable as the sim starts up, you can reduce the concentration but still observe the temperature increase as sunlight first reaches the earth. This was just one example of temperature being a slowly responding depending variable dependent on incoming radiation, concentration, and other things.

@arouinfar is going to note this in the teacher tips but we are ready to close this one.
