### ISSUE TITLE
Energy Balance sound out-of-sync with description

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#203]
@Matthew-Moore240 and I noticed the Energy Balance sound for the first time today during our description meeting. There is a serious mismatch between the sound and description associated with the Energy Balance. This is particularly problematic because the Extra Sounds are designed to support users with visual disabilities who are likely to use a screen reader.

Here's a recording of the a11y view with VO. Please disregard the repeated statements -- I recorded this in Chrome which isn't supported for use with VO. That said, the offset between the Energy Balance description and sounds is very similar in VO/Safari.

https://user-images.githubusercontent.com/8419308/183772834-dc1dd50f-330e-440d-816f-88f38759618f.mp4

The beeping starts 3-4 seconds before the Energy Balance object response is triggered. While not ideal, this is likely due to the other statements in the utterance queue (IR redirecting, surface warming, IR emitted) and I don't think we should be interrupting those. However, there is a 10-second delay between the end of the beeping and the Energy Balance equilibrium statement, which is problematic. The beeping ends when the Net arrow is too small to see (around 0:17). However, the model isn't actually at equilibrium until much later, presumably when the Energy Balance statement is triggered at 0:27.

Tagging for discussion at design meeting.

**Comment by jbphet** [comment]
@arouinfar - I'm happy to look at this, but it feels a little premature.  This is an in-progress feature, see https://github.com/phetsims/greenhouse-effect/issues/143 and https://github.com/phetsims/greenhouse-effect/issues/84.

I understand that we are trying to get a version ready for interviews, and I've published two dev versions towards that goal, but it seems to be taking quite a while to actually do the interviews.  If continuing to develop on master while we are waiting is going to cause issues like this to be logged, we should publish an RC version and fix issues there.

**Comment by jessegreenberg** [comment]
We discussed this today and I think the energy balance sounds were made hidden behind "enhanced"  sounds, or possibly behind a query param. We decided for now to continue with dev versions and tests for upcoming interviews. Removing my assignment.

**Comment by jbphet** [comment]
The energy balance sounds are indeed now behind the "Extra Sounds" settings in the Preferences dialog.  Still, much of the behavior is the same as @arouinfar describes above once these extra sounds are enabled.  So, I have two questions.

First, @arouinfar says above:

> The beeping starts 3-4 seconds before the Energy Balance object response is triggered. While not ideal, this is likely due to the other statements in the utterance queue (IR redirecting, surface warming, IR emitted) and I don't think we should be interrupting those.

The reason for the 3-4 second delay is actually because many of the object responses occur based on a periodic timer which is currently running every 4 seconds.  If you reset the sim, show the energy balance indicator, and restart the sunlight several times, you'll see that there is a lot of variation in the amount of time between starting the sunlight and getting this notification.

It would be possible to change this so that all of the object responses that are on the timer occur shortly after sunlight is started.  We could essentially reset the time interface each time sunlight starts, if that would be ideal.  Should we do that?

Second, @arouinfar also says:

>  [T]here is a 10-second delay between the end of the beeping and the Energy Balance equilibrium statement, which is problematic.

I could adjust the thresholds for these to be the same, which would mean that the beeping would go on for longer.  Should I do that?

**Comment by jbphet** [comment]
@arouinfar - I was just thinking about the 2nd of the two items I've listed above, and I've come to the conclusion that it makes a lot of sense to use the model property that tracks whether the Earth-sun system is in radiative balance to gate the production of sounds for the energy balance sound generator.  This would make it naturally sync up with the object responses.  I'll move forward with that, and have you review it.

**Comment by jbphet** [comment]
@arouinfar - I've added code that links the sound production to the model property that tracks whether the atmosphere is in radiative balance with the sun.  This works a lot better (in my opinion).  However, because the energy balance equilibrium alert is driven by the 4-second polling interval (discussed above), the turning off of the sound generation often happens a few seconds before the alert.  It's up to you whether this is good enough or requires more changes.

Also, please don't forget that we still need an answer to the first question in https://github.com/phetsims/greenhouse-effect/issues/203#issuecomment-1232127952.

**Comment by arouinfar** [comment]
>  I've added code that links the sound production to the model property that tracks whether the atmosphere is in radiative balance with the sun. This works a lot better (in my opinion). 

I completely agree, it's working much better! Thanks @jbphet.

> However, because the energy balance equilibrium alert is driven by the 4-second polling interval (discussed above), the turning off of the sound generation often happens a few seconds before the alert.

The delay doesn't sound too unreasonable, and I can make sure to document this in the Teacher Tips.

> We could essentially reset the time interface each time sunlight starts, if that would be ideal. Should we do that?

I tested this out a bit in VO/Safari, and I'm not bothered by the current behavior. I don't think it's necessary to restart the timer, so I think we can go ahead an close.
