### ISSUE TITLE
Check colors and color profile

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#223]
In the 11/16/2022 design meeting we discussed whether we should consider using `PhetColorScheme.RED_COLORBLIND` for the IR wave depictions.  @arouinfar said that she generally likes to test this sort of thing out by using the color profile, which wasn't available at the time.  I have now added it, so we can do this and address a couple of other things as well.  Here are the questions that come to my mind now that we have a color profile:

- [x] Should we use `PhetColorScheme.RED_COLORBLIND` for the waves?  We were leaning towards deciding *not* to use it during the design meeting discussion, since it's rather orange, and thus not as clearly different from the yellow visible light.
  - Decision: No, don't use it.  The contrast is worse.
- [x] Are there any other things that should be controllable via the color profile?  I added a number of things, but we could really go overboard with this, so we should identify a minimal set.
- [x] Since this makes it easier to experiment with some aspects of the color scheme, are there any changes to the general scheme that would improve things visually?
- [x] Do we need to add a projector profile and, if so, what colors shall we use in it?
  - @arouinfar says we don't need this.

Over to @arouinfar for her responses.

**Comment by jbphet** [comment]
@arouinfar has suggested that the stroke used for selected radio buttons go into the profile.  I'll do that.

**Comment by jbphet** [comment]
I've added the radio button stroke to the color profile.  I'll unassign myself.  @arouinfar - Let me know if any other changes are needed.

**Comment by arouinfar** [comment]
@jbphet the color profile looks good. I can't think of anything else to add at this time.

We reviewed this during a recent-ish design meeting, but for the record using red and yellow for the light works well. Using `PhetColorScheme.RED_COLORBLIND` is not a good idea here because the orange tinge makes it harder to distinguish from yellow. Here's what things currently look like:

| Protanopia | Deuteranopia | 
| --- | --- | 
| <img width="926" alt="image" src="https://user-images.githubusercontent.com/8419308/208540018-2173dd51-46d2-484d-ad2b-8e0ef769f49a.png"> |  <img width="925" alt="image" src="https://user-images.githubusercontent.com/8419308/208540105-71210338-1627-44e1-9fa7-9ee499230ae2.png"> |
| <img width="924" alt="image" src="https://user-images.githubusercontent.com/8419308/208539730-9a3dd420-2530-4bd4-947c-474da8d6e35f.png"> | <img width="928" alt="image" src="https://user-images.githubusercontent.com/8419308/208539629-edda7b8b-801b-41fe-893b-c031ad679484.png"> | 

@jbphet I woul like to change radioButtonGroupSelectedStroke to `rgb(0, 148, 189)`. Currently, it does not pass WCAG standards, so we should darken it a bit. Here's a comparison:

| New: `rgb(0, 148, 189)` | Current: `rgb(0, 173, 221)` |
| --- | --- |
| <img width="398" alt="image" src="https://user-images.githubusercontent.com/8419308/208538901-5496daee-ba91-4c3f-8f06-51fe0a4f3edb.png"> | <img width="394" alt="image" src="https://user-images.githubusercontent.com/8419308/208538831-b65856e5-f521-4862-b861-e976209c03e5.png"> |

**Comment by jbphet** [comment]
The change to the radioButtonGroupSelectedStroke has been made.  It's subtle, but I can definitely see it when doing A+B comparisons.  @arouinfar - Please double check that this is what you're after, and this issue can be closed if there is nothing further to do on the color profile.

**Comment by arouinfar** [comment]
Thanks @jbphet! It is indeed a subtle change, but I wanted to maintain a similar appearance while providing sufficient contrast. The change looks good in master, closing.
