### ISSUE TITLE
Should a description of extra sounds be added?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#237]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/871, but has more general implications.
I've noticed that the sounds added with "extra sounds" may not be immediately clear. This can make testing harder, but it also occurs to me that a short description of what would be added in the preferences dialog may help users know if they need/want to add those sounds and what to listen for.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by emily-phet** [comment]
@KatieWoe Thanks for the suggestion. 
We're aiming for as little as possible sim-specific content in the preferences menu, that's why there's currently no description of the extra sounds (they're sim-specific).
When a sim is published, it comes with a Sound Features video that describes and demonstrates within a pedagogical context all the sounds in the sim. We utilize that in lieu of descriptions within the sim.
