### ISSUE TITLE
Review static description on waves screen and update spec

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#24]
@jessegreenberg and I have done the first round of implementation for the static portion of the description for the waves screen.  The work that was done was based on the [Interactive Description Design spec](https://docs.google.com/document/d/1HWVypTlzM5oSUhhcv7gPdx1sSCs0j-xgIF3lbSgzwAQ/edit?usp=sharing), and the a11y view of a dev version can be found at https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.0-dev.9/phet/greenhouse-effect_a11y_view.html.  At yesterday's design meeting, we decided that it's time for @arouinfar and @Matthew-Moore240 to review what has been done so far and update the spec.  Changes to the spec should be annotated with some searchable tag such as "JB spec update" so that they can be easily found and incorporated into the sim's source code.

Once the spec has been updated, please assign this issue back to me and I'll get them into the sim.

**Comment by arouinfar** [comment]
@jbphet @jessegreenberg the help text for the Waves screen is ready for implementation. The help text is highlighted in cyan in this section: https://docs.google.com/document/d/1HWVypTlzM5oSUhhcv7gPdx1sSCs0j-xgIF3lbSgzwAQ/edit#heading=h.enfahlvtbk6h

@Matthew-Moore240 and I also noticed that the heading order in the a11y view does not match the table in https://docs.google.com/document/d/1HWVypTlzM5oSUhhcv7gPdx1sSCs0j-xgIF3lbSgzwAQ/edit#heading=h.gamh8gxjx7g5. The Clouds checkbox and Energy Balance checkbox should be the last two elements in the Play Area.

**Comment by arouinfar** [comment]
@Matthew-Moore240 and I finished cleaning up the state descriptions for the Waves screen, updates since last time include the H3: Observation Window and H4: Energy Balance. 

We started working on defining the ranges/scales in the Parameters for States & Responses section of the doc, but it's not ready for implementation yet. We're currently working on the greenhouse gas concentration ranges, and in doing so, we've realized that we may need to slightly adjust the wording elsewhere in the descriptions.

For example, there are statements like, "the greenhouse gas concentration is {{qualitative value}}" but that doesn't flow with the language we are considering for the {{qualitative value}}. So we may need to reword things to be more like, "greenhouse gases in atmosphere are {{very concentrated}}". @jbphet @jessegreenberg I would recommend pausing on the implementation on state descriptions for now.

**Comment by jbphet** [comment]
@arouinfar said:

> @jbphet @jessegreenberg I would recommend pausing on the implementation on state descriptions for now.

Sounds good.  We could probably benefit from spending some time on phet-io anyway.  I'm going to unassign @jessegreenberg and myself for now, please add us back once there are items that are ready for the next round of implementation.

**Comment by arouinfar** [comment]
This issue can be rolled into #130, closing.
