### ISSUE TITLE
Odd starting temperatures on the third screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#249]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/871
On the third screen. The temperature displayed starts much lower than it does on other screens, and then rapidly jumps to a more reasonable number as soon as a photon hits the ground. This looks very odd to me and I'm wondering if it is intentional.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
This is intentional, but a good observation.  @arouinfar will add a note to the teach tips about it.  The reason for the lower value in the third screen is that with a high albedo and a low solar input, the temperature can get much lower on this screen, and we start each screen at the lowest temperature and allow them to heat up from there.

I'll close this issue and @arouinfar will follow up in the teacher tips.
