### ISSUE TITLE
Tick label max widths don't match

### ISSUE THREAD

**Issue by marlitas** [phetsims/greenhouse-effect#253]
**Test device**
Mac

**Operating System**
OS 13.01

**Browser**
Chrome

**Problem description**
https://github.com/phetsims/qa/issues/871
The maxWidth for tick labels for the Solar Intensity, Surface Albedo, and Infrared Absorbance sliders do not seem to match, and it looks a bit odd. Would recommend matching those if possible.

**Steps to reproduce**
1. Open Layer Model screen with query parameter `stringTest=double`

**Visuals**
![Screenshot 2023-01-06 at 10 45 31 AM](https://user-images.githubusercontent.com/42476338/211079073-8d593bca-59ed-4b97-9490-c16f347d5bcb.png)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬:‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html?stringTest=double
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1920x944
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by jbphet** [comment]
@arouinfar and I discussed this, and we feel that the behavior is okay as is.  Perhaps this looks a bit odd due to the scaling down of the third slider that is caused be it being in a node with a long title, but since translations are unlikely to have the same length strings, and since many of the labels are using patterns that are unlikely to be lengthened significantly be translators, this doesn't seem worth the time.
