### ISSUE TITLE
Finish adding phet-io support

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#274]
In https://github.com/phetsims/greenhouse-effect/issues/220 we published the 1.1 version of this sim with the "Waves", "Photons", and "Layer Model" screen.  Subsequently in https://github.com/phetsims/greenhouse-effect/issues/268 a decision was made to publish the 1.1 version as a full, non-prototype sim.  Support for phet-io was not complete at that time, so phet-io branded versions were not published.  However, a fair amount of work was done on phet-io during the development process, so a good percentage of the work necessary to add phet-io support is, hopefully, already done.  This issue is to track the addition of the remaining bits.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/tandem/issues/295#issuecomment-1569046569, ReferenceArrayIO was added to support keeping the same Array reference while setting state. @jbphet, please follow the "full" state schema pattern, with no need to provide a `toStateObject` OR an `applyState`. 

Please also note how I have provided type parameters to IOType. This should always be done, but has not become required for typescript due to challeneges over in https://github.com/phetsims/tandem/issues/263

**Comment by jbphet** [comment]
We've gone through the whole process for this, including code review, studio tree review, dev and RC testing, and I just finished the production build of the first full phet-io version of the sim, which is version 1.2.  I think this issue can now be closed.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by zepumph** [comment]
Looks like this is working for issues in the `#274` style in addition to the full URL. nice! https://github.com/phetsims/greenhouse-effect/blob/1cb3ba18fb92f1300c519b9dd6809b5655769936/js/common/view/ConcentrationModelAlerter.ts#L97

**Comment by jbphet** [comment]
Oops, wrong issue number.  Should have been 374, not 274.  Fixed, closing.
