### ISSUE TITLE
Different ranges for albedo in model and view.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#316]
Noted while working on https://github.com/phetsims/greenhouse-effect/issues/311

In GroundLayer.ts, the range is [0,1]:

```ts
    this.albedoProperty = new NumberProperty( options.initialAlbedo, {
      range: new Range( 0, 1 ),
```

In SurfaceAlbedoControl.ts, the range is [0, 0.9]:

```
    // convenience variable
    const surfaceAlbedoRange = new Range( 0, 0.9 );
```

Why is there a different range for model vs view?  Why can't `albedoProperty.range` be [0,0.9] and used in the view?

**Comment by jbphet** [comment]
This was fixed while working on https://github.com/phetsims/greenhouse-effect/issues/317.  I initially did it this way because technically speaking the range for an albedo is 0 to 1, we just limit it to a max of 0.9 in the sim.  After considering it, I think it seems reasonable to have the 0.9 max limit in the model so that phet-io users can't set that value, since we never test it.  I made that change, and added a comment to explain why.  Closing.
