### ISSUE TITLE
Different UI for the Thermometer on the Model screen

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#32]
I noticed that the Model screen as a UI to change the units of temperature like this:
![image](https://user-images.githubusercontent.com/6396244/118038739-7e672d00-b33d-11eb-8bcb-c6728c88d30b.png)

While the other screens use a ComboBox. @arouinfar was this difference intentional, or should both screens use the same component for this?

**Comment by arouinfar** [comment]
Great question @jessegreenberg. The needs a bit different for the Model screen, in particular:
* Each temperature readout should be able to be turned on/off independently of the others (supports predictive questioning).
* All temperature readouts should have the same units so that they easily compared.

A ComboBox would not work for this screen. Changing one ComboBox would require changing the others so that the units are always the same across all readouts. This would be a weird UX, and probably not supported by ComboBox.

Technically, we could have the temperature units RadioButtonGroup on the Waves and Photons screens instead of a ComboBox. I think we may have considered it at some point but decided against it because the space under the observation window is already a bit crowded. The ComboBox is also a nicer UX when there's only one thermometer, and it's a pattern that we've used in many sims.

**Comment by jessegreenberg** [comment]
OK, sounds good, thanks @arouinfar.
