### ISSUE TITLE
Unable to hide individual temp units

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#345]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/970
The instructions in the examples doc mention hiding different temp units and give the following elements for the first two screens. None seem to exist in either Featured or All elements.

>greenhouseEffect.wavesScreen.view.observationWindow.surfaceThermometer.comboBox.listBox.celsiusItem.visibleProperty
greenhouseEffect.wavesScreen.view.observationWindow.surfaceThermometer.comboBox.listBox.fahrenheitItem.visibleProperty
greenhouseEffect.wavesScreen.view.observationWindow.surfaceThermometer.comboBox.listBox.kelvinItem.visibleProperty
greenhouseEffect.photonsScreen.view.observationWindow.surfaceThermometer.comboBox.listBox.celsiusItem.visibleProperty
greenhouseEffect.photonsScreen.view.observationWindow.surfaceThermometer.comboBox.listBox.fahrenheitItem.visibleProperty
greenhouseEffect.photonsScreen.view.observationWindow.surfaceThermometer.comboBox.listBox.kelvinItem.visibleProperty

**Comment by arouinfar** [comment]
How strange. Good find @KatieWoe.

In #341 I requested that `view.observationWindow.surfaceThermometer.comboBox.item` be uninstrumented because it only contained instrumented text. I wonder if @jbphet accidentally also got rid of its sibling `comboBox.listBox` while he was in there.

@jbphet can you take a look?

**Comment by jbphet** [comment]
I think I've got it sorted out.  The easiest way to remove 'items' is to not add a tandem to the individual items, and that's what I did, but it also removed the items from the list box.  I reverted that part and removed the tandems from the individual number displays and value patterns, and that seems to have done the trick.

@arouinfar - Please double check the behavior on main.  It's a little weird because it's possible to hide the item that is currently selected from the list box, and the selection doesn't change, but it's gone from pop-up list box.  I guess that's okay, but thought I should have you confirm.

**Comment by arouinfar** [comment]
@jbphet the behavior on main looks good to me. Closing.

> It's a little weird because it's possible to hide the item that is currently selected from the list box, and the selection doesn't change, but it's gone from pop-up list box. I guess that's okay, but thought I should have you confirm.

This is to be expected and is not unique to ListBox (can happen with radio buttons too). This is a case where people can do strange things with PhET-iO, but we don't expect them to. The sim doesn't crash in this scenario, and users can still interact with the ListBox.
