### ISSUE TITLE
Temperature units switch back to default when setting state

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#356]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/973 and probably due to the fix for  https://github.com/phetsims/greenhouse-effect/issues/352:
 If the temperature units on any screen are changed while in studio/state (ex. from ℃ to K), the launched sim will open in the default units (℃). 

**Steps to reproduce**
Here is an example:
1. In studio, on the Layers Screen, select the K radio button. 
2. Press test 

**Visuals**

https://github.com/phetsims/greenhouse-effect/assets/87318828/ca0561f8-bb7f-42ca-a73f-1d2d31d0b416

**Comment by jbphet** [comment]
Well, this is exactly why I said that the behavior described in #352 [might actually be correct](https://github.com/phetsims/greenhouse-effect/issues/352#issuecomment-1683070952).  Sims launched from Studio are supposed to start with and reset to the state that the user configured.  Yet in #352 @arouinfar said "[[C]ontrols in the Preferences menu are not supposed to be overridden by the ResetAllButton[.]](https://github.com/phetsims/greenhouse-effect/issues/352#issuecomment-1683083307)", so I changed the reset behavior to set the temperature units based on the preferences.  Since launch state and post-reset-all states are the same in the standard wrapper, this overruling of the user configuration by the preferences value also happens during the launch.  We can't have it both ways.  Either the units are set to the preferences value or the value configured by the user.  

I suppose we could start distinguishing between the launch state and the post-reset-all state, but I think the phet-io guys would be mightily opposed to that.

@arouinfar - The question of whether or not Preference menu settings overrule user-configured state may be a bigger issue that you need to work out with the phet-io team.  I'll leave that up to you.  In the interests of getting this sim out the door with phet-io, my inclination would be to revert the changes made for #352 and say that the resulting behavior - i.e. the sim resets to the user-configured state and ignores the preferences setting - is, at least for now, the correct behavior.  Over to you for a ruling.

**Comment by zepumph** [comment]
@samreid and I were able to make a small change to the fix to get the "best of both worlds". The ideal behavior is now implemented, as discussed with @jbphet @arouinfar @samreid:

1. Studio launch/standard wrapper should load the selected unit identically to what the state was from studio.
2. Reset should reset back to the "Default" preference, and not back to the state.

This should be ready for cherry pick.

Please note that @samreid don't love this code long term, but love it for you publication. We are currently working on a few improvements to the state engine on `main` to make this work easier in the future. See https://github.com/phetsims/phet-io/issues/1958

**Comment by arouinfar** [comment]
Thanks @zepumph @samreid! The behavior on main is great. I reviewed the examples doc, and I don't believe any further changes are necessary, so over to @jbphet for next steps.

**Comment by samreid** [comment]
Great, thanks for testing. https://github.com/phetsims/greenhouse-effect/commit/2a5e11b07a13ec238e9633ec2c691fb543408227 is ready for cherry picking. Please be careful since in https://github.com/phetsims/phet-io/issues/1958 we are going to make further changes for LayersModel that are **not** supposed to be cherry picked.

**Comment by jbphet** [comment]
I've cherry-picked the commit to the 1.2 branch, so this is ready to verify in the next QA test.

QA team: The behavior we decided upon and want to verify is that the sim launches in whatever units the user has configured in Studio, but resets to whatever is selected in the Preferences menu.

**Comment by Nancy-Salpepi** [comment]
This is working nicely in rc.2. Closing.
