### ISSUE TITLE
Translation error for degrees Fahrenheit 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#358]
While testing https://github.com/phetsims/qa/issues/973, I noticed that for the locale: ar_MA the translator changed ℉ to °K. 

<img width="172" alt="Screenshot 2023-08-24 at 5 20 48 PM" src="https://github.com/phetsims/greenhouse-effect/assets/87318828/7b52a12d-3969-43ca-903b-5f28b10b1cb0">

**Comment by oliver-phet** [comment]
@Nancy-Salpepi since you are regularly finding translation mistakes, it is probably best if you start directly reporting to the translator:

1. Locate the translated .json file in Babel. [Example Greenhouse in ar_MA](https://github.com/phetsims/babel/blob/master/greenhouse-effect/greenhouse-effect-strings_ar_MA.json)
2. Find the string in question and note the userID value. "458291" in this case
3. (Must be logged in as a team member) Navigate to https://phet.colorado.edu/en/edit-user-access/nnnnnn replacing "nnnnnn" with the userID. Example: https://phet.colorado.edu/en/edit-user-access/458291
4. Use the 'primary email' of the translator to email them about the issue. You can sign in to phethelp@gmail.com if that's most comfortable.

**Comment by Nancy-Salpepi** [comment]
I sent an email to the translator. Once I hear back/see the correction, I will close this issue.

**Comment by jbphet** [comment]
I'm going to unassign myself from this one.  @Nancy-Salpepi - Please let me know if you don't hear back and in that case I could just fix it manually.

**Comment by Nancy-Salpepi** [comment]
The translator made the correction. Closing.
