### ISSUE TITLE
Missing dependencies for DerivedProperties

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#383]
Related to https://github.com/phetsims/axon/issues/441 ...

When run with `?strictAxonDependencies=true`, greenhouse-effecf fails in multiple places with missing dependencies for DerivedProperties.  All of these missing dependencies appear to be related to description strings.

**Comment by jbphet** [comment]
I fixed the two remaining cases.  In one of them I simply added all the string Properties that were potentially used in the creationof the description string to the dependences of the `DerivedProperty`.  However, in the other case the list of dependencies was too long for the type definition of `DerivedProperty`.  Apparently, `DerivedProperty` currently maxes out at 15 dependences, and I needed 19.  I reached out on Slack for suggestions on how to best deal with this, and @samreid suggested I try `Multilink.multilinkAny`.  This worked, and I committed it, but it feels like a bit of a loophole because it doesn't seem to check the dependencies the way `DerivedProperty` does.

This should work okay, and it will be a long time before description strings are dynamic, and we may be using an entirely different approach by then, so I'm okay with what we've got here.  @samreid - can you have one last look at the commit above and make sure that I correctly understood your suggestion?  If so, feel free to close this issue.

**Comment by samreid** [comment]
The changes look reasonable, but I believe I miscommunicated and there is opportunity for improvement. My message from slack is:

```ts
  /**
   * Create a DerivedProperty from any number of dependencies.  This is parallel to Multilink.multilinkAny
   */
  public static deriveAny
```

This is a static method in `DerivedProperty`. So I think you could continue using DerivedProperty here via DerivedProperty.deriveAny. Sorry for the miscommunication about "parallel to ..."

**Comment by jbphet** [comment]
My bad - I didn't read @samreid's Slack message carefully enough.  I've updated the code to use `deriveAny` and it seems much better.  I think this is good and can be closed.
