### ISSUE TITLE
IR updates heard when sim is paused

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#389]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3.1

**Browser**
Safari 17.3.1 + VoiceOver

**Problem description**
When I was testing potential fixes for https://github.com/phetsims/greenhouse-effect/issues/385, I noticed that when the sim is paused, any changes to the amount of Absorbing Layers, Surface Albedo or Solar Intensity trigger the infrared radiation alerts. This is different behavior than what happens on the first 2 screens when I move the Greenhouse Gas Concentration slider while the sim is paused. There I am only told about the amount of Greenhouse Gas. 
This is not specific to VoiceOver because I also see it in a11yview. 

Was this intentional behavior?

**Steps to reproduce**
1. In a11yview or with VO on, go to the Layer Model Screen and press the Start Sunlight button.
2. Use keyboard nav or mouse to press Pause 
3. Use keyboard nav or mouse to change the amount of absorbing layers, surface albedo or solar intensity

**Visuals**
<img width="1440" alt="Screenshot 2024-02-13 at 4 29 23 PM" src="https://github.com/phetsims/greenhouse-effect/assets/87318828/a2841042-2951-491d-b4c3-945a90f2c602">

**Comment by jbphet** [comment]
I saw this issue go by, so I thought I'd comment and investigate to help inform the decision making on it.  I believe we linked the description of the change (e.g. "Layer 1 added above surface") and the effect of that change (e.g. "More infrared photons emitting from surface....") closely together so that they would be next to each other in the utterance queue, and therefore close to one another in time.  We may not have considered the case where the sim was paused when this design decision was made.

The behavior doesn't seem terrible to me, since it is describing the effect of the change.  However, if changes are needed, here are some notes about what would be easy and what wouldn't be:

- It would be pretty straightforward to block all of these alerts until the sim was unpaused, though that doesn't seem like great behavior to me.
- It wouldn't be too hard to leave off the effect if the sim was paused, and just describe the change.
- It *would* be challenging to describe the change but not describe the effect until the sim was unpaused.

Hope that helps.

**Comment by arouinfar** [comment]
Good observation @Nancy-Salpepi, thanks for opening this issue.

> The behavior doesn't seem terrible to me, since it is describing the effect of the change. 

I agree @jbphet. Thanks for providing some alternative options. I think we can leave this as-is. It's a little weird, but it's not incorrect. I worry a bit that stopping or delaying these alerts would be more trouble than it's worth.
