### ISSUE TITLE
Redirected IR Wave Flashes when Greenhouse Gas Levels Change

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#401]
**Test device**
MacBook Air M1 chip

**Operating System**
14.4.1

**Browser**
Safari and Chrome

**Problem description**

For https://github.com/phetsims/qa/issues/1080 and seen in published, on the Waves Screen the center IR wave redirecting back  to the surface will flash when increasing greenhouse gas levels from None to Lots. 
It is easier to see this using keyboard navigation but happens with the mouse as well. 

Not sure if this falls in the "artifacts" category that was discussed in https://github.com/phetsims/greenhouse-effect/issues/84. 

**Steps to reproduce**

1. On the Waves Screen, press Start Sunlight
2. With keyboard nav, move the Greenhouse Gas slider to None
3. With keyboard nav, move the slider to Lots --keeping an eye on the center IR wave redirecting back to the surface

**Visuals**

https://github.com/phetsims/greenhouse-effect/assets/87318828/f2b0c239-0622-4d85-80ec-f0bf21f4c165

**Comment by arouinfar** [comment]
Good find @Nancy-Salpepi.

The flickering looks a bit odd, but I don't think it's particularly harmful. @jbphet if there's not a clear solution, I'm fine with closing as wont-fix.

**Comment by jbphet** [comment]
The problematic behavior was due to the intensity changes that are tracked on each wave getting a little out of order.  I believe I've corrected this.

@Nancy-Salpepi - Could you please test this on main?  I'd like to verify that it's fixed on whatever platforms and in whatever use cases you were using.

**Comment by samreid** [comment]
I observed that CT indicated https://github.com/phetsims/greenhouse-effect/commit/86d9389974891190455ca6ca82f94ba3bc554666 caused this error:

```
greenhouse-effect : migration : 1.2->main : assert
http://128.138.93.172/continuous-testing/ct-snapshots/1715204138894/phet-io-wrappers/migration/?sim=greenhouse-effect&oldVersion=1.2&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1715204138894%22%2C%22timestamp%22%3A1715205857681%7D
Uncaught TypeError: this.intensityChanges.updateOrder is not a function
TypeError: this.intensityChanges.updateOrder is not a function
at updateOrder (Wave.ts:285:26)
at step (WavesModel.ts:188:41)
at Array.forEach
at forEach (PhetioGroup.ts:183:65)
at forEach (WavesModel.ts:188:19)
at stepModel (GreenhouseEffectModel.ts:74:11)
at step (Sim.ts:432:21)
at apply (PhetioAction.ts:162:16)
at execute (Sim.ts:1048:30)
at stepSimulation (Sim.ts:1038:11)
```

<img width="897" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/679486/0215e9e7-f7ab-46e7-b272-d033759f47fd">

<img width="774" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/679486/76cde7d2-bd08-4a26-a812-4d9659797110">

**Comment by jbphet** [comment]
Thanks @samreid.  This error is due to some phet-io complications with some changes that I made that I felt would improve the maintainability of this code and prevent problems like this from creeping in again.  However, my changes create a new type, which has to be handled in phet-io, and because this new type extends `Array`, I wasn't at all sure how to handle it in phet-io.  I was also concerned that it would also create migration problems.  So, I'm just going back to a simpler solution and hope that future developers see and adhere to the documentation about maintaining the order of the intensity changes.

@Nancy-Salpepi - assuming CT clears up, this is ready for you to test as described above.

**Comment by Nancy-Salpepi** [comment]
Looks fixed on main. 
Not sure if I should close or not, so assigning back to you @jbphet.

**Comment by jbphet** [comment]
This issue can and should be closed once verified by QA on an RC version.

**Comment by Nancy-Salpepi** [comment]
Looks good in 1.3.0-rc.1! Closing.
