### ISSUE TITLE
Dev version needed for early sound interviews and sound mockups

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#55]
Over Slack, @BLFiedler said:

> Hey John! I have some interviews lined up in the next week starting Thursday and @emily-phet mentioned there was some sonification on the Greenhouse Waves screen that might be good to quickly pop in front of folks. Do you have a dev link I could use for that?

Also, @Ashton-Morris is in the process of creating some mockups for sound design of the waves screen.  To serve the purposes of both, I'm going to create a dev version with the latest behavior for the waves screen and the sound that goes along with it.

**Comment by jbphet** [comment]
The dev version has been published, @Ashton-Morris and @BLFiedler - please see https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.0-dev.13/phet/greenhouse-effect_en_phet.html.

**Comment by BLFiedler** [comment]
Two interviews were conducted on 7/29/2021 with college students (P1 & P2) experienced on an iPad in Safari.

Link used was: https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.0-dev.13/phet/greenhouse-effect_en_phet.html?screens=1

### General
- Both participants were able to make the connection between increasing greenhouse gas concentration and increasing surface temperature. Both participants were able to identify the increasing thickness of the IR waves with increasing GH gas (GHG) concentration. Both participants appreciated the presence of both direct GH gas conc slider and the time period comparison. Both identified the difference in directionality of IR and Sunlight waves. P1 did not notice the reflecting IR from the increasing GH. Both made use of the energy balance display. P2 did not understand the surface temperature visualization toggle until making more extreme GHG slider changes.

### Sound and Sonifications
- Neither participant commented on the sounds during exploration.
- Neither participant noticed the change in the continuous sound or the GHG slider sound until explicitly asked.
 - P1 described the sound as "eerie elevator music", but did note the quickness/pitch increase with increased GH concentration, and slower/lower with less. P2 recognized a pitch increase at higher
 - Neither participant was able to directly connect the sound to the surface temperature, even when switching on and off the surface thermometer. 
- Both participants were able to identify the pitch change with the GHG slider after being asked to explore it further. Both approved of the sounds.
- Neither commented on the sound design being annoying during their interaction, but both verbalized during questioning that it could become annoying. (BF: I believe this thought mostly occurred because they were asked. Neither seemed bothered by it while they were exploring).
- Both expressed the desire to be able to turn off the sound without disabling the thermometer.

### Potential Bugs
- I think this is tied to our continued, sporadic issues with iPad/mobile devices, but after awhile in both interviews the sounds would become crackly. A page refresh would fix it, but eventually it would happen again.

**Comment by BLFiedler** [comment]
I have two more interviews lined up next week, and I may put this in front of one or both of them depending on other interview needs. Let me know if you have any questions I can answer about the interviews, if you'd like me to come to a sound design meeting, or if you have other questions I can focus on for upcoming interviews if they occur.

**Comment by BLFiedler** [comment]
Tagging @emily-phet as she may be interested.

**Comment by BLFiedler** [comment]
Just to re-emphasize: This was done on iPad speakers and the sonification changes may be more noticeable with headphones or higher quality speakers.

**Comment by emily-phet** [comment]
Some reflections from me:
- I think this seems like a fine sound to move forward with the upcoming August deadline.
- Once there are sounds additionally for the waves and photons, how people perceive the ambient sounds could change (with more or less awareness of the mapping as the sound is now).
- I think it will be useful, for helping the design of GHE as we add in more sounds, and also for our general understanding of ambient sounds in sims, to explore in interviews versions of the ambient temperature sounds where the mapping is made more emphatic. The next steps for variants of the ambient temperature that serve this purpose are being discussed in issue #36. I'd like to see what it takes to get that mapping more overt, and to see how that impacts learners sim use. Then we will have more information to help us decide what is the response we'd like, one where the mapping is more explicit, or more in the background (as it seems to be now).

**Comment by BLFiedler** [comment]
I would just like to add in a few notes from this last interview where I quickly threw in GHE Waves after some haptics interviews, once again on an iPad.

- Again, generally the concepts acquired via visual feedback and interaction allowed the participant to "get" the simulation and connect the GHG concentration to the changes in the incoming and resultant waves, transmission and reflection, and surface temperature changes.

- During exploration, the participant did not understand the connection between the sound and the visibility toggle of the surface thermometer, similar to other interviews.
- The participant did not map any changes to the sounds through interaction during the questioning period, even when asked to re-explore. I asked that they turn up the volume to the max and explore some more and they then finally recognized the mapping for the ambient sound and correctly associated it with the surface temperature upon realizing it did not change at the same time they change the slider.

(BF)**This part I think is a bit important and unique to this interview:**
- When asked more about the change, they commented that 1.) they really were not paying much attention to the sound during exploration and 2.) the delay in sound changes made it less noticeable as it did not map directly to their actions. They did acknowledge the significance of the delay (in that it maps to the surface temp which is also delayed in reacting to the GHG concentration change), but that it just made it register a bit less on their radar as they moved forward.

- Again, there was no sense that the sound disturbed their interaction/exploration during free explore and nothing found to be annoying about the sound.

**Comment by jbphet** [comment]
We (the sound design team) have referenced this issue in the sound design doc and feel like we're ready to close.
