### ISSUE TITLE
Sun can shine in studio while the "Start Sunlight" button is visible

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#61]
From PhET-iO Studio you can set `isShiningProperty` to true, then back to false. The first time it is set to true, the 'Start Sunlight' button becomes invisible. When you set it back to false, the "start sunlight" button becomes visible again but the visible waves continue to propagate from the sun.

**Comment by jessegreenberg** [comment]
While meeting with @arouinfar we noticed that when this happens we aren't seeing any infrared waves or the temperature rising. It is almost like a view bug where the sun stops shining, but visible waves continue to be drawn. This definitely seems buggy I will investigate.

**Comment by jessegreenberg** [comment]
I think what we probably need to do is clear the waves again when `sunEnergySource.isShiningProperty` is false. This patch accomplishes it

```patch
Index: js/common/view/ObservationWindow.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/ObservationWindow.js	(revision 23baecb2ecb13b18494e8c8aaa0926bfd72eebe3)
+++ js/common/view/ObservationWindow.js	(date 1628115793091)
@@ -394,6 +394,10 @@
         }
         darknessNode.visible = true;
         darknessNode.opacity = DARKNESS_OPACITY;
+
+        // clear all waves when the sun stops shining (either from simulation or when set externally
+        // from PhET-iO or something else)
+        model.waves.length = 0;
       }
     } );
 
Index: js/waves/model/WavesModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/waves/model/WavesModel.js	(revision 23baecb2ecb13b18494e8c8aaa0926bfd72eebe3)
+++ js/waves/model/WavesModel.js	(date 1628115808195)
@@ -353,7 +353,6 @@
    */
   reset() {
     super.reset();
-    this.waves.length = 0;
     this.surfaceTemperatureVisibleProperty.reset();
     this.cloudReflectedWavesMap.clear();
     this.sunWaveSource.reset();
```

But Ill wait to apply this one until the waves-instrumentation branch has been merged into master because it involves the model.waves which is about to become a PhetioGroup.

**Comment by jbphet** [comment]
@jessegreenberg and I discussed this during our weekly collaboration meeting, and decided to simply set `isShiningProperty` to be phet-io read-only.  Our reasoning is that the users can't just turn off the sun from the sim's UI, so there probably wouldn't be a need to do so via studio either.  Also, if we _did_ support turning off the sun, the sim should probably respond by letting the waves that are present at that moment continue to propagate until they were fully absorbed by the ground, and subsequently the Earth would cool to the minimum temperature supported by the sim and IR waves would stop coming out of the ground, which seems like it could be a bit misleading (since in reality, they Earth would continue to radiate IR until it reached absolute zero).

@arouinfar - Let us know if you disagree with this call.  It would be quite a bit more work to support turning off the sun, but it could be done, and we'd need to decide on the details of the behavior.  If you're good with what we've done here, feel free to close.

**Comment by jessegreenberg** [comment]
This behavior of the visible waves makes a lot of sense, thanks @jbphet. I noticed that the IR waves git thin immediately when the visible light stops. Is that expected?

**Comment by jbphet** [comment]
>  I noticed that the IR waves get thin immediately when the visible light stops. Is that expected? It looks like the temperature immediately drops to 245 K when the sunlight stops as well, not sure if that is related.

Yes, as soon as the sun stops, the temperature cools down very quickly.  This is the flip side of making the ground heat up quickly in response to the sunlight, i.e., it also cools off quickly if the sunlight is removed.  In other words, this is a natural consequence of other design choices that we've made.

Since the question was raised, I'll assign this to @arouinfar to make a call on whether this behavior is acceptable or if we need to change something about it.

**Comment by jbphet** [comment]
@arouinfar and I reviewed this in the design meeting today and we're good with the updated behavior.  Closing.
