### ISSUE TITLE
IR waves returning to earth aren't connected to original wave

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#66]
**Test device**
MacBook Air (M1 chip)

**Operating System**
11.4

**Browser**
Safari 14.1.1

**Problem description**
https://github.com/phetsims/qa/issues/690

In the WAVES screen, when the IR wave hits the atmosphere and splits, the wave that continues to space, still seems "connected" to the original IR wave, while the one returning to earth is "disconnected." 

**Visuals**
<img width="243" alt="Screen Shot 2021-08-17 at 8 29 52 AM" src="https://user-images.githubusercontent.com/87318828/129731995-ef244cf5-516c-4f19-91f3-15a13af3d044.png">

<img width="170" alt="Screen Shot 2021-08-17 at 8 29 24 AM" src="https://user-images.githubusercontent.com/87318828/129732155-9879fdb0-be9f-4dfc-8ad1-752d43126d5a.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.0-dev.15/phet/greenhouse-effect_en_phet.html
Version: 1.0.0-dev.15 2021-08-08 00:56:43 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
Language: en-us
Window: 1440x683
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by jbphet** [comment]
I've added a first cut of code to adjust the sine waves so that the appear to originate from and interact with horizontal layers, and this greatly improves how well the waves meet up.  I'd like to do some optimization and further testing before saying that this is fixed.

**Comment by jbphet** [comment]
I have an algorithm in place that works reasonably well.  It uses an approximation to calculate the amount of compensation necessary to make waves appear as though they originate from and interact with horizontal surfaces.  I worked for a while to try to come up with an exact, analytical solution to the issue of how to calculate this, and it turned out to be pretty difficult.  I also did a little work on coming up with an iterative approach for getting reasonably precise values, but felt like this approach would potentially have performance issues.

In the end, my approach was to calculate the point of interest on a wave, rotate it by the angle at which the wave is propagating, and use the distance of the y-value from the horizontal surface as the compensation amount.  Visually this seems like a big improvement, and the calculation is very quick so it had a negligible impact on performance.

The next question is whether this is good enough.  @arouinfar - please check the current behavior on master and either give it your blessing or hit it back to me for further work.

**Comment by jbphet** [comment]
@arouinfar, @kathy-phet, and I reviewed the behavior in today's design meeting and we've decided that this is good as is and I shouldn't invest any more time in trying to improve it, at least for now.

**Comment by Nancy-Salpepi** [comment]
Waves look connected now. I don't see any disconnect.

**Comment by jbphet** [comment]
Closing.  I think it's unlikely that I'll put any more time into this to make the last bit of improvement, but if I do, I'll reopen.
