### ISSUE TITLE
Escape key does not exit dialogs

### ISSUE THREAD

**Issue by stemilymill** [phetsims/greenhouse-effect#88]
for https://github.com/phetsims/qa/issues/707
Noticed on multiple platforms

Hitting the escape key does not exit dialogs and menus.

*Keystrokes are shown at the bottom of the video:*

https://user-images.githubusercontent.com/85511101/133819123-17f6cb0d-dd6d-4989-8a10-d4b86749f3bb.mp4

**Comment by jessegreenberg** [comment]
Thanks @stemilymill - This one is happening because https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.0-rc.1/phet/greenhouse-effect_all_phet.html is going out with Interactive Description disabled. This means that no keyboard input will  be working yet. I just tested that using `?supportsInteractiveDescription=true` query param has the escape key closing dialogs.
